# Config to log IP from X-Forwarded-For header
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      log_format custom '$http_x_forwarded_for - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';

      access_log /var/log/nginx/access.log custom;

      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri $uri/ =404;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: web
      name: web-svc
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: calebs-taco-truck
        imagePullPolicy: Never # built locally
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - name: nginx-logs
            mountPath: /var/log/nginx
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      - name: splunk-uf
        image: splunk/universalforwarder:10.0
        env:
          - name: SPLUNK_START_ARGS
            value: --accept-license
          - name: SPLUNK_GENERAL_TERMS
            value: --accept-sgt-current-at-splunk-com
          - name: SPLUNK_PASSWORD
            value: password
          - name: SPLUNK_CMD
            value: add monitor /var/log/nginx/access.log
          - name: SPLUNK_STANDALONE_URL
            value: splunk.default.svc.cluster.local
        volumeMounts:
          - name: nginx-logs
            mountPath: /var/log/nginx
      volumes:
      - name: nginx-logs
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: splunk-scaledobject
spec:
  cooldownPeriod: 1
  pollingInterval: 3
  minReplicaCount: 1
  maxReplicaCount: 3
  scaleTargetRef:
    name: nginx
  triggers:
  - type: splunk
    authenticationRef:
      name: splunk-auth
    metadata:
      host: https://splunk.default.svc.cluster.local:8089
      unsafeSsl: "true"
      targetValue: "10"
      activationValue: "0" # ignore, for cold start implementations
      savedSearchName: taco-truck-customers
      valueField: count
